# Generated by Django 4.2.4 on 2023-08-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('psg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Window_Model',
            new_name='Main_page_window_model',
        ),
    ]
