# Generated by Django 4.2.4 on 2023-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psg', '0003_resolution_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution_model',
            name='description',
            field=models.TextField(),
        ),
    ]
