# Generated by Django 4.2.4 on 2023-09-08 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psg', '0004_alter_resolution_model_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
