# Generated by Django 4.2 on 2024-03-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psg', '0010_image_three_image_two_rename_image_image_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_three',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='image_two',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='Image_one',
        ),
        migrations.DeleteModel(
            name='Image_three',
        ),
        migrations.DeleteModel(
            name='Image_two',
        ),
    ]
